[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./" }
]

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@1inch/=node_modules/@1inch/"
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
